version: '3.8'

services:
  web:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/companor
      - APP_NAME=companor
    env_file:
      - .env
    networks:
      - companor_network

  mongo:
    image: iobaidu5/mongodb-companor
    ports:
      - "27017:27017"
    volumes:
      - companor_db:/data/db
    networks:
      - companor_network

volumes:
  companor_db:

networks:
  companor_network:
    driver: bridge
